name: cresign
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 6.1.0
  sticky_headers: 0.3.0+2
  lottie: 2.7.0
  firebase_core: ^2.22.0
  google_sign_in: 6.1.6
  firebase_auth: ^4.13.0
  google_sign_in_web: 0.12.1
  cloud_firestore: ^4.13.0
  faker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

